// productos.js

// Función para obtener la ruta correcta de las imágenes según la ubicación
function getImagePath(imagePath) {
  // Detectar si estamos en la carpeta pages/ de manera más robusta
  const currentPath = window.location.pathname;
  const isInPagesFolder = currentPath.includes('/pages/');
  
  // Siempre usar rutas absolutas desde la raíz del sitio
  const correctedPath = '/' + imagePath;
  
  console.log('🖼️ Image path correction:');
  console.log('  Current path:', currentPath);
  console.log('  Original:', imagePath);
  console.log('  Is in pages folder:', isInPagesFolder);
  console.log('  Corrected:', correctedPath);
  
  return correctedPath;
}

// Función para procesar las imágenes de un producto
function processProductImages(producto) {
  return {
    ...producto,
    imagenes: producto.imagenes.map(img => getImagePath(img))
  };
}

const productos = [
  {
    id: 1,
    nombre: "Gorro de lana",
    descripcion: "Gorro tejido a mano con lana merino de alta calidad. Perfecto para el invierno. Súper abrigado y suave al tacto.",
    imagenes: ["img/gorro00.jpeg", "img/gorro01.jpeg"],
    precio: 2500,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Natural", "Rosa", "Gris", "Negro"],
    tiempoProduccion: "5-7 días",
    destacado: true,
    stock: 5,
    talles: ["Único"],
  },
  {
    id: 2,
    nombre: "Cardigan",
    descripcion: "Cardigan de lana súper abrigado. Talle XXL. Ideal para los días más fríos. Tejido con lana de primera calidad.",
    imagenes: [
      "img/cardigan00.jpeg",
      "img/cardigan01.jpeg",
      "img/cardigan02.jpeg",
      "img/cardigan03.jpeg",
      "img/cardigan04.jpeg",
    ],
    precio: 3800,
    categoria: "ropa",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Beige", "Gris", "Rosa palo", "Azul marino"],
    tiempoProduccion: "10-15 días",
    destacado: true,
    stock: 3,
    talles: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 3,
    nombre: "Mitones de lana",
    descripcion: "Mitones súper calentitos y prácticos. Perfectos para usar tu celular sin pasar frío. En el color y tamaño que prefieras.",
    imagenes: ["img/mitones_lana00.jpeg", "img/mitones_lana01.jpeg"],
    precio: 5600,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Natural", "Mostaza", "Verde", "Bordo"],
    tiempoProduccion: "5-7 días",
    destacado: true,
    stock: 8,
    talles: ["S", "M", "L"],
  },
  {
    id: 4,
    nombre: "Bufanda tejida",
    descripcion: "Bufanda gruesa para invierno, suave y cálida. Extra larga para dar varias vueltas. Material hipoalergénico.",
    imagenes: ["img/bufanda.jpg", "img/bufanda00.jpg", "img/bufanda01.jpg"],
    precio: 3200,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Beige", "Gris", "Negro", "Bordo"],
    tiempoProduccion: "7-10 días",
    destacado: false,
    stock: 4,
    talles: ["Único"],
  },
  {
    id: 5,
    nombre: "Saquito de bebé de 1 año",
    descripcion: "Saquito hecho en cashmilon fino. Ideal para media estación. Suave, abrigado y perfecto para los más pequeños.",
    imagenes: ["img/saquito_bebe00.jpg"],
    precio: 4500,
    categoria: "ropa",
    temporada: "otoño",
    personalizable: true,
    coloresDisponibles: ["Blanco", "Rosa", "Celeste", "Beige"],
    tiempoProduccion: "7-10 días",
    destacado: false,
    stock: 3,
    talles: ["1 año"],
  },
  {
    id: 6,
    nombre: "Bolso-cartera",
    descripcion: "Bolso-cartera tejido a mano con hilo de algodón con seda. Diseño elegante en color blanco y negro. Perfecto para cualquier ocasión.",
    imagenes: ["img/bolso_cartera00.jpg", "img/bolso_cartera01.jpg", "img/bolso_cartera02.jpg"],
    precio: 6500,
    categoria: "accesorios",
    temporada: "todo el año",
    personalizable: true,
    coloresDisponibles: ["Blanco y Negro", "Negro y Beige", "Gris y Blanco"],
    tiempoProduccion: "12-15 días",
    destacado: false,
    stock: 2,
    talles: ["Único"],
  },
  {
    id: 7,
    nombre: "Poncho triangular",
    descripcion: "Poncho triangular tejido en lana de alta calidad. Súper calentito y elegante. Perfecto para los días más fríos. Diseño versátil que se adapta a cualquier look.",
    imagenes: ["img/poncho.jpg", "img/poncho00.jpg", "img/poncho01.jpg"],
    precio: 8500,
    categoria: "ropa",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Gris", "Beige", "Negro", "Bordo", "Verde musgo"],
    tiempoProduccion: "15-20 días",
    destacado: true,
    stock: 4,
    talles: ["Único"],
  },
  {
    id: 8,
    nombre: "Chaleco de lana",
    descripcion: "Chaleco tejido a mano perfecto para media estación. Liviano pero abrigado, ideal para usar sobre camisas o remeras. Diseño clásico y atemporal.",
    imagenes: ["img/chaleco.jpg"],
    precio: 3500,
    categoria: "ropa",
    temporada: "otoño",
    personalizable: true,
    coloresDisponibles: ["Camel", "Gris oxford", "Azul petróleo", "Verde militar"],
    tiempoProduccion: "10-12 días",
    destacado: false,
    stock: 5,
    talles: ["S", "M", "L", "XL"],
  },
  {
    id: 9,
    nombre: "Cuello Infinity",
    descripcion: "Cuello circular infinito súper suave y abrigado. Se puede usar simple o doble vuelta. Perfecto compañero para el frío. Tejido en lana merino extra suave.",
    imagenes: ["img/cuello.jpg", "img/cuello00.jpg"],
    precio: 2800,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Mostaza", "Bordo", "Gris perla", "Natural"],
    tiempoProduccion: "5-7 días",
    destacado: false,
    stock: 6,
    talles: ["Único"],
  },
  {
    id: 10,
    nombre: "Guantes de lana",
    descripcion: "Guantes completos tejidos a mano con lana de primera calidad. Súper abrigados para los días más fríos. Perfectos para proteger tus manos del viento y el frío.",
    imagenes: ["img/guantes.jpg"],
    precio: 3200,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Negro", "Gris", "Beige", "Rosa palo"],
    tiempoProduccion: "7-10 días",
    destacado: false,
    stock: 7,
    talles: ["S", "M", "L"],
  },
  {
    id: 11,
    nombre: "Manta/Throw",
    descripcion: "Manta decorativa tejida a mano perfecta para el sillón o la cama. Tamaño generoso de 1.20m x 1.50m. Cálida, suave y hermosa. Una pieza de decoración funcional.",
    imagenes: ["img/manta.jpg"],
    precio: 12500,
    categoria: "ropa",
    temporada: "todo el año",
    personalizable: true,
    coloresDisponibles: ["Gris y blanco", "Beige y natural", "Azul y blanco", "Rosa y gris"],
    tiempoProduccion: "20-25 días",
    destacado: false,
    stock: 2,
    talles: ["120x150cm"],
  },
  {
    id: 12,
    nombre: "Sweater Oversize",
    descripcion: "Sweater tejido a mano estilo oversize, súper cómodo y trendy. Perfecto para un look casual y relajado. Tejido en lana gruesa con punto inglés.",
    imagenes: ["img/sweater.jpg"],
    precio: 7800,
    categoria: "ropa",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Crudo", "Gris melange", "Camel", "Negro"],
    tiempoProduccion: "15-18 días",
    destacado: false,
    stock: 3,
    talles: ["Único (oversize)"],
  },
  {
    id: 13,
    nombre: "Payasito Plim Plim",
    descripcion: "Muñeco Plim Plim tejido a mano en lana suave. El personaje favorito de los más chicos. Ideal para regalo. Aproximadamente 35cm de alto.",
    imagenes: ["img/plimplim.jpg"],
    precio: 5500,
    categoria: "juguetes",
    temporada: "todo el año",
    personalizable: false,
    coloresDisponibles: ["Tradicional (rojo, amarillo, azul)"],
    tiempoProduccion: "10-12 días",
    destacado: true,
    stock: 2,
    talles: ["Único"],
  },
  {
    id: 14,
    nombre: "Set de mate y latitas recicladas",
    descripcion: "Set artesanal con mate y latitas decoradas con crochet. Incluye mate de calabaza o madera + 2 latitas recicladas tejidas para yerbera y azucarera. Ecológico y único.",
    imagenes: ["img/set_mate.jpg"],
    precio: 6800,
    categoria: "hogar",
    temporada: "todo el año",
    personalizable: true,
    coloresDisponibles: ["Natural", "Beige y blanco", "Gris y crudo", "Colores a elección"],
    tiempoProduccion: "7-10 días",
    destacado: true,
    stock: 3,
    talles: ["Único"],
  },
  {
    id: 15,
    nombre: "Medias de lana",
    descripcion: "Medias largas tejidas a mano hasta la rodilla. Súper abrigadas y cómodas para estar en casa. Lana suave que no pica. Perfectas para el invierno.",
    imagenes: ["img/medias.jpg"],
    precio: 3800,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Natural", "Gris", "Rosa palo", "Beige", "Bordo"],
    tiempoProduccion: "7-10 días",
    destacado: false,
    stock: 6,
    talles: ["35-38", "39-42"],
  },
  {
    id: 16,
    nombre: "Ruana",
    descripcion: "Ruana tejida a mano en lana suave y calentita. Prenda versátil perfecta para abrigarte con estilo. Diseño amplio y cómodo que combina con todo.",
    imagenes: ["img/ruana.jpg", "img/ruana00.jpg"],
    precio: 7500,
    categoria: "ropa",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Gris", "Beige", "Camel", "Bordo", "Verde musgo", "Azul petróleo"],
    tiempoProduccion: "15-18 días",
    destacado: true,
    stock: 3,
    talles: ["Único"],
  },
  {
    id: 17,
    nombre: "Gorritos y cuellitos para bebé de 1 año",
    descripcion: "Set de gorrito y cuellito tejidos a mano para bebé de 1 año. Lana extra suave e hipoalergénica. Perfectos para proteger del frío a los más pequeños. Diseño tierno y abrigado.",
    imagenes: ["img/set_bebe.jpg"],
    precio: 4200,
    categoria: "accesorios",
    temporada: "invierno",
    personalizable: true,
    coloresDisponibles: ["Blanco", "Rosa", "Celeste", "Beige", "Gris claro"],
    tiempoProduccion: "7-10 días",
    destacado: true,
    stock: 4,
    talles: ["1 año"],
  },
  {
    id: 18,
    nombre: "Bolso tejido",
    descripcion: "Bolso amplio tejido a mano en hilo de algodón. Perfecto para uso diario, playa o compras. Resistente y con gran capacidad. Diseño moderno y versátil.",
    imagenes: ["img/bolso_tejido.jpg", "img/bolso_tejido00.jpg"],
    precio: 5800,
    categoria: "accesorios",
    temporada: "todo el año",
    personalizable: true,
    coloresDisponibles: ["Natural", "Beige", "Gris", "Negro", "Camel", "Combinados"],
    tiempoProduccion: "10-12 días",
    destacado: false,
    stock: 5,
    talles: ["Único"],
  },
  {
    id: 19,
    nombre: "Aritos tejidos",
    descripcion: "Aritos/pendientes tejidos a mano en hilo de algodón con estructura de metal. Livianos y cómodos. Diseños únicos y modernos. Perfectos para uso diario o casual.",
    imagenes: ["img/aritos.jpg", "img/aritos00.jpg", "img/aritos01.jpg", "img/aritos02.jpg"],
    precio: 1500,
    categoria: "accesorios",
    temporada: "todo el año",
    personalizable: true,
    coloresDisponibles: ["Natural", "Negro", "Bordo", "Mostaza", "Verde", "Combinados"],
    tiempoProduccion: "3-5 días",
    destacado: false,
    stock: 10,
    talles: ["Único"],
  },
  {
    id: 20,
    nombre: "Capelina con moño",
    descripcion: "Elegante capelina tejida a mano con lazo decorativo. Sombrero de ala ancha perfecto para verano, playa o eventos especiales. Estilo romántico y sofisticado.",
    imagenes: ["img/capelina.jpg", "img/capelina00.jpg", "img/capelina01.jpg"],
    precio: 4500,
    categoria: "accesorios",
    temporada: "verano",
    personalizable: true,
    coloresDisponibles: ["Natural", "Blanco", "Negro", "Beige", "Rosa palo"],
    tiempoProduccion: "8-10 días",
    destacado: true,
    stock: 4,
    talles: ["Único"],
  },
  {
    id: 21,
    nombre: "Hombre Araña",
    descripcion: "Muñeco del Hombre Araña tejido a mano en lana. El superhéroe favorito de los chicos. Perfecto para regalo o colección. Aproximadamente 30cm de alto.",
    imagenes: ["img/spiderman.jpg"],
    precio: 5200,
    categoria: "juguetes",
    temporada: "todo el año",
    personalizable: false,
    coloresDisponibles: ["Tradicional (rojo y azul)"],
    tiempoProduccion: "10-12 días",
    destacado: true,
    stock: 3,
    talles: ["Único"],
  },
];

// Definir combos/paquetes especiales
const combos = [
  {
    id: 101,
    nombre: "Combo Invierno Completo",
    descripcion: "El pack perfecto para el frío: Gorro + Mitones + Bufanda. ¡Ahorrá $2000!",
    productos: [1, 3, 4],
    precioOriginal: 11300,
    precio: 9300,
    descuento: 2000,
    imagenes: ["img/combo1.jpg"],
    destacado: true,
  },
  {
    id: 102,
    nombre: "Pack Regalo Perfecto",
    descripcion: "Ideal para regalar: Gorro + Mitones. Un detalle que abriga manos y cabeza con estilo.",
    productos: [1, 3],
    precioOriginal: 8100,
    precio: 6900,
    descuento: 1200,
    imagenes: ["img/combo2.jpg"],
    destacado: true,
  },
  {
    id: 103,
    nombre: "Combo Invierno Premium",
    descripcion: "El pack más completo para el invierno: Poncho + Gorro + Mitones. Máxima protección y estilo. ¡Ahorrá $1800!",
    productos: [7, 1, 3],
    precioOriginal: 16600,
    precio: 14800,
    descuento: 1800,
    imagenes: ["img/combo3.jpg"],
    destacado: true,
  },
];

// Procesar todas las imágenes para que funcionen desde cualquier ubicación
console.log('🔄 Processing images for all products and combos...');
console.log('📍 Current location:', window.location.pathname);

const productosConRutasCorregidas = productos.map(processProductImages);
const combosConRutasCorregidas = combos.map(combo => ({
  ...combo,
  imagenes: combo.imagenes.map(img => getImagePath(img))
}));

console.log('✅ Processed products:', productosConRutasCorregidas.length);
console.log('✅ Processed combos:', combosConRutasCorregidas.length);

// Exportar las versiones procesadas
window.productos = productosConRutasCorregidas;
window.combos = combosConRutasCorregidas;

console.log('📤 Exported to window.productos and window.combos');
